-- ============================================================================
-- Nostalgia Radio — foundation schema
--   categories → stations → songs          (the catalogue: code stays the
--                                            source of truth, seeded from Git)
--   suggestions + votes + station_events   (the community layer)
--
-- Design rules
--   • Audio bytes never live here — only pointers (audio_url / playlist_url).
--   • Vote counts are never stored; they are counted from `votes` rows and
--     published through the `suggestion_vote_counts` view.
--   • Every public write is validated server-side (CHECK constraints +
--     triggers), so a hand-crafted request cannot bypass the UI's rules.
--     The limits mirror src/lib/request-api.ts exactly:
--       – 3 suggestions / 60 s per visitor
--       – 10 votes / 60 s per visitor
--       – one row per provider song id, ever (duplicates refused)
--   • Idempotent: safe to re-run in the Supabase SQL Editor.
--
-- After this file, run (in order):
--   20260930000002_rls_policies.sql
--   20260930000003_seed_catalogue.sql   (generated by `npm run seed:sql`)
-- ============================================================================

create extension if not exists pgcrypto; -- gen_random_uuid() (built-in since PG13)

-- ----------------------------------------------------------------------------
-- CATEGORIES — the hero's station selectors (chips), ordered and toggleable
-- ----------------------------------------------------------------------------
create table if not exists public.categories (
  id            uuid primary key default gen_random_uuid(),
  name          text not null check (length(btrim(name)) between 1 and 80),
  slug          text not null unique check (slug ~ '^[a-z0-9-]+$'),
  tagline       text check (tagline is null or length(tagline) between 1 and 300),
  icon          text check (icon is null or length(icon) <= 8),
  accent        text check (accent is null or accent ~ '^#[0-9a-fA-F]{6}$'),
  image_url     text check (image_url is null or length(image_url) between 1 and 500),
  -- Station slug (not FK: the flagship row may be seeded in either order).
  flagship_slug text check (flagship_slug is null or length(flagship_slug) between 1 and 120),
  sort_order    integer not null default 0 check (sort_order >= 0),
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

comment on table public.categories is
  'Hero category chips. Seeded from src/data/categories.ts — edit the code, re-run npm run seed:sql.';

-- ----------------------------------------------------------------------------
-- STATIONS — one row per listening world (mirrors src/types/station.ts)
-- ----------------------------------------------------------------------------
create table if not exists public.stations (
  id                  uuid primary key default gen_random_uuid(),
  category_id         uuid references public.categories(id) on delete set null,
  slug                text not null unique check (slug ~ '^[a-z0-9-]+$'),
  title               text not null check (length(btrim(title)) between 1 and 120),
  description         text check (description is null or length(description) <= 700),
  flagship            boolean not null default false,
  featured            boolean not null default false,
  demo                boolean not null default false,
  region              text check (region is null or length(region) <= 100),
  language            text[],   -- e.g. {Hindi}
  era                 text check (era is null or length(era) <= 60),
  tags                text[],
  -- Local path (/art/…) or absolute https URL.
  artwork_url         text check (artwork_url is null or
                        (length(artwork_url) between 1 and 500 and
                         (artwork_url like '/%' or artwork_url like 'https://%'))),
  -- Hero stage photos, one drawn per page load (see src/lib/backdrop.ts).
  backdrops           jsonb check (backdrops is null or
                        (jsonb_typeof(backdrops) = 'array' and
                         jsonb_array_length(backdrops) <= 12)),
  accent              text check (accent is null or accent ~ '^#[0-9a-fA-F]{6}$'),
  source_url          text check (source_url is null or
                        (length(source_url) between 1 and 1000 and source_url like 'https://%')),
  audio_url           text check (audio_url is null or length(audio_url) between 1 and 1000),
  provider            text check (provider is null or provider in ('youtube', 'spotify')),
  playlist_url        text check (playlist_url is null or
                        (length(playlist_url) between 1 and 1000 and playlist_url like 'https://%')),
  action              text not null default 'check' check (action in ('play', 'check')),
  source_type         text not null default 'external-site'
                        check (source_type in ('external-site', 'direct-audio', 'embed')),
  status              text not null default 'unknown'
                        check (status in ('ready', 'offline', 'unknown')),
  now_playing_title   text check (now_playing_title is null or length(now_playing_title) <= 200),
  now_playing_subtitle text check (now_playing_subtitle is null or length(now_playing_subtitle) <= 240),
  sort_order          integer not null default 0 check (sort_order >= 0),
  active              boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint stations_provider_with_playlist
    check ((provider is null) = (playlist_url is null))
);

comment on table public.stations is
  'Seeded from src/data/stations.ts. Catalogue edits belong in the code; re-run npm run seed:sql to refresh.';

create index if not exists stations_category_idx on public.stations (category_id);
create index if not exists stations_order_idx on public.stations (active, sort_order);

-- ----------------------------------------------------------------------------
-- SONGS — the large, lazily-loaded library (one day: station playlists).
-- Empty at first; the table exists so the UI architecture never has to change.
-- ----------------------------------------------------------------------------
create table if not exists public.songs (
  id           uuid primary key default gen_random_uuid(),
  station_id   uuid not null references public.stations(id) on delete cascade,
  title        text not null check (length(btrim(title)) between 1 and 300),
  artist       text check (artist is null or length(artist) between 1 and 200),
  album        text check (album is null or length(album) <= 200),
  year         smallint check (year is null or (year >= 1850 and year <= 2100)),
  language     text check (language is null or length(language) <= 60),
  duration_sec integer check (duration_sec is null or duration_sec >= 0),
  audio_url    text check (audio_url is null or length(audio_url) between 1 and 1000),
  artwork_url  text check (artwork_url is null or length(artwork_url) between 1 and 500),
  provider     text check (provider is null or provider in ('youtube', 'spotify')),
  provider_id  text check (provider_id is null or length(provider_id) between 1 and 128),
  source_type  text not null default 'direct-audio'
                 check (source_type in ('direct-audio', 'hls', 'stream', 'youtube', 'spotify')),
  active       boolean not null default true,
  sort_order   integer not null default 0 check (sort_order >= 0),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.songs is
  'Per-station track library for later phases. Always fetched paginated (first 20, then more) — never wholesale.';

create index if not exists songs_station_idx on public.songs (station_id);
create index if not exists songs_station_order_idx on public.songs (station_id, active, sort_order);
create index if not exists songs_title_search_idx on public.songs (lower(title));

-- ----------------------------------------------------------------------------
-- SUGGESTIONS — the community request wall ("What should play next?").
-- Mirrors src/lib/request-api.ts: provider identity, honest metadata, a
-- moderation/lifecycle status, and never a stored vote count.
-- ----------------------------------------------------------------------------
create table if not exists public.suggestions (
  id            uuid primary key default gen_random_uuid(),
  song_url      text not null check (length(song_url) between 1 and 1000 and song_url like 'https://%'),
  provider      text not null check (provider in ('youtube', 'spotify')),
  provider_id   text not null check (length(provider_id) between 10 and 64),
  title         text not null check (length(btrim(title)) between 1 and 160),
  artist        text check (artist is null or length(artist) between 1 and 120),
  artwork_url   text check (artwork_url is null or
                  (length(artwork_url) between 1 and 500 and artwork_url like 'https://%')),
  description   text check (description is null or length(description) <= 1000),
  station_id    uuid references public.stations(id) on delete set null,
  status        text not null default 'pending'
                  check (status in ('pending', 'approved', 'rejected', 'played')),
  visitor_token text check (visitor_token is null or length(visitor_token) between 1 and 100),
  played_at     timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint suggestions_played_has_timestamp
    check (status <> 'played' or played_at is not null)
);

comment on table public.suggestions is
  'One row = one community request. Counts/rankings are never stored here.';
comment on column public.suggestions.status is
  'pending = awaiting moderation (invisible to the wall) · approved = votable/open · played = aired to history (never replays) · rejected = refused (invisible)';
comment on column public.suggestions.visitor_token is
  'Random non-identifying device id. Never granted for public SELECT — the wall never receives it.';
comment on column public.suggestions.provider_id is
  'Provider-native track id (YouTube 11 chars / Spotify 22). Unique forever: one song, one request.';

-- Duplicate detection at the database level: a second request for the same
-- song id fails with 23505 no matter who asks (matches the V1 bySong index,
-- which never forgets — played and rejected songs stay unique too).
create unique index if not exists suggestions_one_per_song
  on public.suggestions (provider, provider_id);

create index if not exists suggestions_status_created_idx on public.suggestions (status, created_at);
create index if not exists suggestions_status_played_idx on public.suggestions (status, played_at);
create index if not exists suggestions_station_idx on public.suggestions (station_id);
create index if not exists suggestions_visitor_window_idx on public.suggestions (visitor_token, created_at);
create index if not exists suggestions_title_search_idx on public.suggestions (lower(title));

-- ----------------------------------------------------------------------------
-- VOTES — one row per (target, visitor). The only honest way to count.
-- `mine` is remembered on the device (tab-local, like V1); tokens are never
-- exposed publicly, and the aggregate lives in suggestion_vote_counts.
-- ----------------------------------------------------------------------------
create table if not exists public.votes (
  id            uuid primary key default gen_random_uuid(),
  suggestion_id uuid references public.suggestions(id) on delete cascade,
  station_id    uuid references public.stations(id) on delete cascade,
  visitor_token text not null check (length(visitor_token) between 1 and 100),
  created_at    timestamptz not null default now(),
  constraint votes_exactly_one_target
    check ((case when suggestion_id is not null then 1 else 0 end) +
           (case when station_id  is not null then 1 else 0 end) = 1)
);

comment on table public.votes is
  'One row per (target, visitor). No public SELECT (tokens stay private); counts publish via suggestion_vote_counts.';

-- One vote per visitor per request → the 23505 the UI maps to "already voted".
create unique index if not exists votes_one_per_suggestion
  on public.votes (suggestion_id, visitor_token) where suggestion_id is not null;
create unique index if not exists votes_one_per_station
  on public.votes (station_id, visitor_token) where station_id is not null;

create index if not exists votes_suggestion_idx on public.votes (suggestion_id);
create index if not exists votes_station_idx on public.votes (station_id);
create index if not exists votes_visitor_window_idx on public.votes (visitor_token, created_at);

-- ----------------------------------------------------------------------------
-- STATION_EVENTS — optional background analytics (one event per action,
-- never per second). Write-only for the public; admin reads come later.
-- ----------------------------------------------------------------------------
create table if not exists public.station_events (
  id            uuid primary key default gen_random_uuid(),
  station_id    uuid not null references public.stations(id) on delete cascade,
  event_type    text not null check (event_type in ('play', 'pause', 'skip', 'complete')),
  visitor_token text check (visitor_token is null or length(visitor_token) <= 100),
  created_at    timestamptz not null default now()
);

create index if not exists station_events_station_idx on public.station_events (station_id, created_at);
create index if not exists station_events_created_idx on public.station_events (created_at);

-- ----------------------------------------------------------------------------
-- Server-side rate limits — enforced in the database, so they hold for every
-- path (UI, curl, or a future Edge Function). Limits mirror request-api.ts:
-- 3 submissions and 10 votes per visitor per 60-second window.
-- Rows without a visitor token (dashboard / service-role imports) bypass them.
-- ----------------------------------------------------------------------------
create or replace function public.enforce_suggestion_rate()
returns trigger
language plpgsql
as $$
declare
  recent integer;
begin
  if new.visitor_token is null then
    return new;
  end if;
  select count(*) into recent
    from public.suggestions
   where visitor_token = new.visitor_token
     and created_at > now() - interval '60 seconds';
  if recent >= 3 then
    raise exception 'rate-limited: at most 3 suggestions per minute'
      using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists suggestions_rate_limit on public.suggestions;
create trigger suggestions_rate_limit
  before insert on public.suggestions
  for each row execute function public.enforce_suggestion_rate();

create or replace function public.enforce_vote_rate()
returns trigger
language plpgsql
as $$
declare
  recent integer;
begin
  if new.visitor_token is null then
    return new;
  end if;
  select count(*) into recent
    from public.votes
   where visitor_token = new.visitor_token
     and created_at > now() - interval '60 seconds';
  if recent >= 10 then
    raise exception 'rate-limited: at most 10 votes per minute'
      using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists votes_rate_limit on public.votes;
create trigger votes_rate_limit
  before insert on public.votes
  for each row execute function public.enforce_vote_rate();

-- updated_at stays honest without any client involvement.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists stations_touch_updated on public.stations;
create trigger stations_touch_updated
  before update on public.stations
  for each row execute function public.touch_updated_at();

drop trigger if exists songs_touch_updated on public.songs;
create trigger songs_touch_updated
  before update on public.songs
  for each row execute function public.touch_updated_at();

drop trigger if exists suggestions_touch_updated on public.suggestions;
create trigger suggestions_touch_updated
  before update on public.suggestions
  for each row execute function public.touch_updated_at();

-- ----------------------------------------------------------------------------
-- The only vote count the client may ever see: an aggregate over votes.
-- Runs with owner rights on purpose (no security_invoker) so it can count
-- without granting SELECT on the rows — visitor tokens never leave the DB.
-- ----------------------------------------------------------------------------
drop view if exists public.suggestion_vote_counts;
create view public.suggestion_vote_counts as
  select suggestion_id, count(*)::integer as votes
    from public.votes
   where suggestion_id is not null
   group by suggestion_id;

comment on view public.suggestion_vote_counts is
  'Public, token-free vote totals per suggestion (definer rights: aggregates only).';

-- The view is public data from birth (re-running this migration alone must not
-- leave it unreachable before 000002 re-grants).
grant select on public.suggestion_vote_counts to anon, authenticated;
