-- Generated by `npm run seed:sql` from src/data/categories.ts + src/data/stations.ts.
-- DO NOT EDIT BY HAND — edit the TypeScript catalogue and regenerate.
-- Idempotent: re-running refreshes catalogue fields in place and never touches
-- community data (suggestions / votes / station_events).
-- 8 categories · 37 stations.

insert into public.categories (slug, name, tagline, icon, accent, flagship_slug, sort_order, active)
values
  ('mix', 'Mix', 'A broad nostalgia rotation from every corner of the archive.',
   '✦', '#f05a45', 'nostalgia-radio',
   1, true),
  ('transit', 'Travel', 'Road, bus, highway, railway and journey radio.',
   '🚌', '#e2543a', 'truck-wala-radio',
   2, true),
  ('beyond-india', 'Beyond', 'International and cross-border nostalgia.',
   '🌐', '#d89a54', 'desi-world-radio',
   3, true),
  ('regional-folk', 'Folk', 'Regional folk, language and traditional sounds.',
   '🪘', '#c4633f', 'rajasthani-folk',
   4, true),
  ('ambient', 'Ambient', 'Rain, café, late night, study and atmospheric listening.',
   '🎧', '#e7c88b', 'rain-window-radio',
   5, true),
  ('festival', 'Festivals', 'Holi, Diwali, Chhath, Eid, weddings and seasonal occasions.',
   '🪔', '#e8663a', 'holi-gulal-fm',
   6, true),
  ('work', 'Work', 'Workshops, builders, factories, drivers, offices and trades.',
   '🧵', '#d89a54', 'kaam-wala-radio',
   7, true),
  ('shops', 'Shop', 'Markets, bazaars, street shopping and commercial nostalgia.',
   '🏪', '#f05a45', 'bazaar-radio',
   8, true)
on conflict (slug) do update set
  name = excluded.name, tagline = excluded.tagline, icon = excluded.icon,
  accent = excluded.accent, flagship_slug = excluded.flagship_slug,
  sort_order = excluded.sort_order, active = excluded.active;

insert into public.stations (slug, category_id, title, description, flagship, featured, demo, region, language, era, tags, artwork_url, backdrops, accent, source_url, audio_url, provider, playlist_url, action, source_type, status, now_playing_title, now_playing_subtitle, sort_order, active)
select 'nostalgia-radio', c.id, 'Nostalgia Radio', 'Old roads. Forgotten songs. New memories.', true, true, true, 'Pan India', array['Hindi'], '1960s–2000s', array['nostalgia', 'classic', 'archive', 'memories'], '/art/neighborhood.svg', '["https://i.pinimg.com/1200x/8b/82/8f/8b828f5ce63e57c7c33a759f819544cd.jpg","https://i.pinimg.com/1200x/bd/48/2a/bd482a9fc6fe538cd82938014afd53f6.jpg","https://i.pinimg.com/1200x/9d/c7/55/9dc755f6d5b464cc7f2664aa205da10e.jpg","https://i.pinimg.com/1200x/cc/c4/f0/ccc4f0021b67e6d40aa4b01f0d91d7b4.jpg","https://i.pinimg.com/1200x/37/7e/f8/377ef862b0222fb6ba3381cced861378.jpg","https://i.pinimg.com/1200x/7c/32/ab/7c32abccf5a044047356cb724eb55d65.jpg","https://i.pinimg.com/1200x/b5/3e/3a/b53e3a7d55ae614e7742af481c9440c3.jpg"]'::jsonb, '#f05a45', 'https://example.org/nostalgia-radio', '/audio/demo-a.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape A', 'Synthesised locally · not a licensed track', 1, true
from public.categories c where c.slug = 'mix'
union all
select 'truck-wala-radio', c.id, 'Truck Wala Radio', 'Highway bangers, desi beats and trucker tales from India’s long roads.', true, true, true, 'Highway', array['Hindi'], '1990s–2000s', array['road', 'highway', 'people', 'memories'], '/art/highway.svg', null, '#e2543a', 'https://example.org/truck-wala-radio', '/audio/demo-a.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape A', 'Synthesised locally · not a licensed track', 2, true
from public.categories c where c.slug = 'transit'
union all
select 'desi-world-radio', c.id, 'Desi World Radio', 'Indian melodies carried across borders — diaspora, disco and long-distance longing.', true, true, true, 'International', array['Hindi', 'English'], '1970s–2000s', array['world', 'diaspora', 'oldies'], '/art/cafe.svg', null, '#d89a54', 'https://example.org/desi-world-radio', '/audio/demo-c.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape C', 'Synthesised locally · not a licensed track', 3, true
from public.categories c where c.slug = 'beyond-india'
union all
select 'rain-window-radio', c.id, 'Rain Window Radio', 'Slow nostalgic evening music for balconies, kettles and unhurried rain.', true, true, true, 'Pan India', array['Hindi'], '1980s–2000s', array['rain', 'evening', 'slow'], '/art/rainy-street.svg', null, '#e7c88b', 'https://example.org/rain-window-radio', '/audio/demo-b.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape B', 'Synthesised locally · not a licensed track', 4, true
from public.categories c where c.slug = 'ambient'
union all
select 'kaam-wala-radio', c.id, 'Kaam Wala Radio', 'Background radio for workshops, desks, delivery runs and the ten-hour shift.', true, true, true, 'North India', array['Hindi'], '1990s–2000s', array['workshop', 'focus', 'shift'], '/art/workshop.svg', null, '#d89a54', 'https://example.org/kaam-wala-radio', '/audio/demo-c.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape C', 'Synthesised locally · not a licensed track', 5, true
from public.categories c where c.slug = 'work'
union all
select 'bazaar-radio', c.id, 'Bazaar Radio', 'Shopfront speakers, bargaining energy and the market’s own playlist.', true, true, true, 'Pan India', array['Hindi'], '1980s–2000s', array['bazaar', 'market', 'street'], '/art/market.svg', null, '#f05a45', 'https://example.org/bazaar-radio', '/audio/demo-a.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape A', 'Synthesised locally · not a licensed track', 6, true
from public.categories c where c.slug = 'shops'
union all
select 'musafir', c.id, 'Musafir', 'Drive your own truck: highway ballads, horn melodies and open-road dhol.', false, true, true, 'North India', array['Hindi', 'Punjabi'], '1970s–1990s', array['road', 'truck', 'highway'], '/art/highway.svg', null, null, 'https://example.org/musafir', '/audio/demo-a.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape A', 'Synthesised locally · not a licensed track', 7, true
from public.categories c where c.slug = 'transit'
union all
select 'highway-47', c.id, 'Highway 47', 'Mile-marker music for night buses and the long way home.', false, false, false, 'North India', array['Hindi'], '1980s', array['night drive', 'bus'], '/art/highway.svg', null, null, 'https://example.org/highway-47', null, null, null, 'check', 'external-site', 'unknown', null, null, 8, true
from public.categories c where c.slug = 'transit'
union all
select 'auto-wallah-fm', c.id, 'Auto Wallah FM', 'City-cutting playlists for autos, meter readings and monsoon traffic.', false, false, false, 'Metro', array['Tamil', 'Hindi'], '1990s–2000s', array['city', 'auto', 'monsoon'], '/art/rainy-street.svg', null, null, 'https://example.org/auto-wallah-fm', null, null, null, 'check', 'external-site', 'unknown', null, null, 9, true
from public.categories c where c.slug = 'transit'
union all
select 'train-window', c.id, 'Train Window', 'Railway platform announcements, cassette ballads and window-seat weather.', false, false, false, 'Pan India', null, '1970s–1990s', array['rail', 'journey'], '/art/railway.svg', null, null, 'https://example.org/train-window', null, null, null, 'check', 'external-site', 'offline', null, null, 10, true
from public.categories c where c.slug = 'transit'
union all
select 'dhaba-nights', c.id, 'Dhaba Nights', 'Chai, dal and the songs that start after the last truck parks.', false, false, false, 'Punjab', array['Hindi'], '1980s–1990s', array['dhaba', 'night'], '/art/tea-stall.svg', null, null, 'https://example.org/dhaba-nights', null, null, null, 'check', 'external-site', 'unknown', null, null, 11, true
from public.categories c where c.slug = 'transit'
union all
select 'r-s-world', c.id, 'R''s World', 'Border-hopping nostalgia: global oldies picked like postcards from elsewhere.', false, true, true, 'International', array['English'], '1960s–1980s', array['world', 'oldies'], '/art/cafe.svg', null, null, 'https://example.org/rs-world', '/audio/demo-c.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape C', 'Synthesised locally · not a licensed track', 12, true
from public.categories c where c.slug = 'beyond-india'
union all
select 'istanbul-ferry', c.id, 'Istanbul Ferry', 'Strait breezes, ferry horns and mid-century melodies from the Bosphorus.', false, false, false, 'Turkey', null, '1960s–1970s', array['ferry', 'europe'], '/art/neighborhood.svg', null, null, 'https://example.org/istanbul-ferry', null, null, null, 'check', 'external-site', 'unknown', null, null, 13, true
from public.categories c where c.slug = 'beyond-india'
union all
select 'vinyl-tokyo', c.id, 'Vinyl Tokyo', 'City-pop grooves and convenience-store midnight frequencies.', false, false, false, 'Japan', null, '1980s', array['city pop', 'vinyl'], '/art/night-desk.svg', null, null, 'https://example.org/vinyl-tokyo', null, null, null, 'check', 'external-site', 'unknown', null, null, 14, true
from public.categories c where c.slug = 'beyond-india'
union all
select 'cape-town-coast', c.id, 'Cape Town Coast', 'Coastal harmonies, guitar dust and long summer evenings.', false, false, false, 'South Africa', null, '1970s–1990s', array['coast', 'acoustic'], '/art/rainy-street.svg', null, null, 'https://example.org/cape-town-coast', null, null, null, 'check', 'external-site', 'offline', null, null, 15, true
from public.categories c where c.slug = 'beyond-india'
union all
select 'rajasthani-folk', c.id, 'Rajasthani Folk', 'Desert strings, langa vocals and camels-walk-slowly rhythms.', true, true, true, 'Rajasthan', array['Marwari', 'Hindi'], 'Traditional', array['folk', 'desert'], '/art/desert.svg', null, '#c4633f', 'https://example.org/rajasthani-folk', '/audio/demo-b.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape B', 'Synthesised locally · not a licensed track', 16, true
from public.categories c where c.slug = 'regional-folk'
union all
select 'kassita', c.id, 'Kassita', 'Roots recordings with a rough edge — village fairs, hand drums and open air.', false, false, false, 'Rural India', null, 'Traditional', array['folk', 'fair'], '/art/market.svg', null, null, 'https://example.org/kassita', null, null, null, 'check', 'external-site', 'unknown', null, null, 17, true
from public.categories c where c.slug = 'regional-folk'
union all
select 'baul-bhavan', c.id, 'Baul Bhavan', 'Ektara devotion and wandering-minstrel songs from Bengal.', false, false, false, 'West Bengal', array['Bengali'], 'Traditional', array['baul', 'devotional'], '/art/neighborhood.svg', null, null, 'https://example.org/baul-bhavan', null, null, null, 'check', 'external-site', 'unknown', null, null, 18, true
from public.categories c where c.slug = 'regional-folk'
union all
select 'bihu-feed', c.id, 'Bihu Feed', 'Assamese harvest drums and spring-time dance rounds.', false, false, false, 'Assam', array['Assamese'], 'Traditional', array['harvest', 'dance'], '/art/festival.svg', null, null, 'https://example.org/bihu-feed', null, null, null, 'check', 'external-site', 'unknown', null, null, 19, true
from public.categories c where c.slug = 'regional-folk'
union all
select 'malnad-lullaby', c.id, 'Malnad Lullaby', 'Slow Karnataka folk for rainy afternoons and open verandas.', false, false, false, 'Karnataka', array['Kannada'], 'Traditional', array['lullaby', 'rain'], '/art/rainy-street.svg', null, null, 'https://example.org/malnad-lullaby', null, null, null, 'check', 'external-site', 'unknown', null, null, 20, true
from public.categories c where c.slug = 'regional-folk'
union all
select 'purane-naghme', c.id, 'Purane Naghme', '90s Hindi songs remembered from cassette inserts — soft, warm and unhurried.', false, true, true, 'Pan India', array['Hindi'], '1990s', array['cassette', '90s', 'soft'], '/art/bus.svg', null, null, 'https://example.org/purane-naghme', '/audio/demo-a.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape A', 'Synthesised locally · not a licensed track', 21, true
from public.categories c where c.slug = 'ambient'
union all
select 'rainy-study-hall', c.id, 'Rainy Study Hall', 'Fan hum, pen scratches and monsoon windows for long focus sessions.', false, false, false, 'Pan India', null, '2000s', array['focus', 'rain'], '/art/rainy-street.svg', null, null, 'https://example.org/rainy-study-hall', null, null, null, 'check', 'external-site', 'unknown', null, null, 22, true
from public.categories c where c.slug = 'ambient'
union all
select 'night-shift-desk', c.id, 'Night Shift Desk', 'Low light, high deadlines: quiet radio for the 2 a.m. hour.', false, false, false, 'Pan India', null, '2000s–2010s', array['work', 'late night'], '/art/night-desk.svg', null, null, 'https://example.org/night-shift-desk', null, null, null, 'check', 'external-site', 'unknown', null, null, 23, true
from public.categories c where c.slug = 'ambient'
union all
select 'tape-hiss', c.id, 'Tape Hiss', 'Nothing but the sound of a cassette deck breathing between tracks.', false, false, false, 'Pan India', null, '1980s', array['tape', 'asmr'], '/art/cafe.svg', null, null, 'https://example.org/tape-hiss', null, null, null, 'check', 'external-site', 'unknown', null, null, 24, true
from public.categories c where c.slug = 'ambient'
union all
select 'chhath-puja-radio-bihar', c.id, 'Chhath Puja Radio — Bihar', 'Riverbank evening aarti, soop offerings and Bhojpuri festival songs.', false, true, true, 'Bihar', array['Bhojpuri', 'Hindi'], 'Traditional', array['chhath', 'aarti'], '/art/festival.svg', null, null, 'https://example.org/chhath-puja-radio', '/audio/demo-b.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape B', 'Synthesised locally · not a licensed track', 25, true
from public.categories c where c.slug = 'festival'
union all
select 'diwali-terrace', c.id, 'Diwali Terrace', 'Firecracker static, thali bells and the songs of every building terrace.', false, false, false, 'Pan India', array['Hindi'], '1990s–2000s', array['diwali', 'family'], '/art/neighborhood.svg', null, null, 'https://example.org/diwali-terrace', null, null, null, 'check', 'external-site', 'unknown', null, null, 26, true
from public.categories c where c.slug = 'festival'
union all
select 'holi-gulal-fm', c.id, 'Holi Gulal FM', 'Drum-lines and drenching-day classics from the corner of the colony.', true, true, true, 'North India', array['Hindi'], '1980s–2000s', array['holi', 'dance'], '/art/festival.svg', null, '#e8663a', 'https://example.org/holi-gulal-fm', '/audio/demo-b.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape B', 'Synthesised locally · not a licensed track', 27, true
from public.categories c where c.slug = 'festival'
union all
select 'morning-aarti', c.id, 'Morning Aarti', 'Temple bells at five, before the city remembers it has a job.', false, false, false, 'Pan India', null, 'Traditional', array['devotional', 'morning'], '/art/railway.svg', null, null, 'https://example.org/morning-aarti', null, null, null, 'check', 'external-site', 'offline', null, null, 28, true
from public.categories c where c.slug = 'festival'
union all
select 'munna-mistri', c.id, 'Munna Mistri', 'Scaffold radio for builders: rhythm for lifting, wiring and chai breaks.', false, true, true, 'North India', array['Hindi'], '1990s–2000s', array['construction', 'labour'], '/art/workshop.svg', null, null, 'https://example.org/munna-mistri', '/audio/demo-c.wav', null, null, 'play', 'direct-audio', 'unknown', 'Demo Tape C', 'Synthesised locally · not a licensed track', 29, true
from public.categories c where c.slug = 'work'
union all
select 'loom-room', c.id, 'Loom Room', 'Shuttle clack and weavers’ radio from the power-loom belt.', false, false, false, 'Maharashtra', null, '1980s–1990s', array['weaving', 'craft'], '/art/workshop.svg', null, null, 'https://example.org/loom-room', null, null, null, 'check', 'external-site', 'unknown', null, null, 30, true
from public.categories c where c.slug = 'work'
union all
select 'cycle-repair-shop', c.id, 'Cycle Repair Shop', 'Pump, puncture, film songs: the smallest workshop with the best speaker.', false, false, false, 'Pan India', null, '1970s–1990s', array['workshop', 'street'], '/art/workshop.svg', null, null, 'https://example.org/cycle-repair-shop', null, null, null, 'check', 'external-site', 'unknown', null, null, 31, true
from public.categories c where c.slug = 'work'
union all
select 'bakery-morning', c.id, 'Bakery Morning', 'Four a.m. ovens, radio warm-ups and the first bread of the day.', false, false, false, 'Gujarat', null, '2000s', array['bakery', 'morning'], '/art/tea-stall.svg', null, null, 'https://example.org/bakery-morning', null, null, null, 'check', 'external-site', 'unknown', null, null, 32, true
from public.categories c where c.slug = 'work'
union all
select 'tapri-talk', c.id, 'Tapri Talk', 'Cutting chai, newspaper arguments and cricket score interruptions.', false, false, false, 'Pan India', array['Hindi'], '1990s–2010s', array['chai', 'street'], '/art/tea-stall.svg', null, null, 'https://example.org/tapri-talk', null, null, null, 'check', 'external-site', 'unknown', null, null, 33, true
from public.categories c where c.slug = 'shops'
union all
select 'salon-oldies', c.id, 'Salon Oldies', 'Mirror-side cassettes, hair-oil fragrance and waiting-room classics.', false, false, false, 'Pan India', null, '1980s–1990s', array['salon', 'barber'], '/art/neighborhood.svg', null, null, 'https://example.org/salon-oldies', null, null, null, 'check', 'external-site', 'unknown', null, null, 34, true
from public.categories c where c.slug = 'shops'
union all
select 'paan-corner', c.id, 'Paan Corner', 'Sweet-lime neon and the song somebody plays every single night.', false, false, false, 'Uttar Pradesh', array['Hindi'], '1990s', array['paan', 'night'], '/art/market.svg', null, null, 'https://example.org/paan-corner', null, null, null, 'check', 'external-site', 'unknown', null, null, 35, true
from public.categories c where c.slug = 'shops'
union all
select 'cyber-cafe-2004', c.id, 'Cyber Café 2004', 'Dial-up tone, printouts and the shared-speaker playlist of an entire generation.', false, false, false, 'Pan India', null, '2000s', array['cyber café', 'y2k'], '/art/night-desk.svg', null, null, 'https://example.org/cyber-cafe-2004', null, null, null, 'check', 'external-site', 'unknown', null, null, 36, true
from public.categories c where c.slug = 'shops'
union all
select 'stationery-shop-radio', c.id, 'Stationery Shop Radio', 'Exam-season requests, geometry boxes and summer-holiday songs.', false, false, false, 'Pan India', null, '1990s–2000s', array['school', 'summer'], '/art/market.svg', null, null, 'https://example.org/stationery-shop', null, null, null, 'check', 'external-site', 'unknown', null, null, 37, true
from public.categories c where c.slug = 'shops'
on conflict (slug) do update set
  category_id = excluded.category_id, title = excluded.title,
  description = excluded.description, flagship = excluded.flagship,
  featured = excluded.featured, demo = excluded.demo, region = excluded.region,
  language = excluded.language, era = excluded.era, tags = excluded.tags,
  artwork_url = excluded.artwork_url, backdrops = excluded.backdrops,
  accent = excluded.accent, source_url = excluded.source_url,
  audio_url = excluded.audio_url, provider = excluded.provider,
  playlist_url = excluded.playlist_url, action = excluded.action,
  source_type = excluded.source_type, status = excluded.status,
  now_playing_title = excluded.now_playing_title,
  now_playing_subtitle = excluded.now_playing_subtitle,
  sort_order = excluded.sort_order, active = excluded.active;
